### ISSUE TITLE
Redo rebase

### ISSUE THREAD

**Issue by ramonaZmole** [AlexandraArdelean/EvozonInternship#7]
Create a new branch rebase2 from this commit 
![image](https://github.com/AlexandraArdelean/EvozonInternship/assets/12456781/22203327-123e-4e87-8a70-3db001520896)

using the rebase command, update the rebase2 branch to have the latest commit from main branch

**Comment by AlexandraArdelean** [comment]
Remade the steps, hope it's ok now. If not, I will start from the beginning :D
