### ISSUE TITLE
Redo merge 

### ISSUE THREAD

**Issue by ramonaZmole** [AlexandraArdelean/EvozonInternship#8]
Create a new branch merge2 from this commit 
![image](https://github.com/AlexandraArdelean/EvozonInternship/assets/12456781/f8ae701f-7e60-4e56-99df-cd127955ca7f)

Using the merge command update the merge2 branch with the latest changes from main

**Comment by AlexandraArdelean** [comment]
Remade the steps, hope it's ok now. If not, I will start from the beginning :D
